cube(`SegCliClientes`, {
  sql: `SELECT * FROM seg_cli_clientes`,

  measures: {
    count: {
      type: 'count',
    },
  },

  dimensions: {
    cli_codigo: { sql: 'cli_codigo', type: 'number' },
    cli_codimf: { sql: 'cli_codimf', type: 'number' },
    cli_codpai: { sql: 'cli_codpai', type: 'number' },
    cli_coddep: { sql: 'cli_coddep', type: 'number' },
    cli_codmun: { sql: 'cli_codmun', type: 'number' },
    cli_codtdi: { sql: 'cli_codtdi', type: 'number' },
    cli_codgen: { sql: 'cli_codgen', type: 'number' },
    cli_codetn: { sql: 'cli_codetn', type: 'number' },
    cli_nombres: { sql: 'cli_nombres', type: 'string' },
    cli_apellidos: { sql: 'cli_apellidos', type: 'number' },
    cli_comarca: { sql: 'cli_comarca', type: 'string' },
    cli_numero_documento: { sql: 'cli_numero_documento', type: 'number' },
    cli_fecha_nacimiento: { sql: 'cli_fecha_nacimiento', type: 'time' },
    cli_estado_civil: { sql: 'cli_estado_civil', type: 'string' },
    cli_sector_rural: { sql: 'cli_sector_rural', type: 'string' },
    cli_numero_hijos: { sql: 'cli_numero_hijos', type: 'number' },
    cli_numero_dependientes: { sql: 'cli_numero_dependientes', type: 'number' },
    cli_escolaridad: { sql: 'cli_escolaridad', type: 'number' },
    cli_ocupacion_primaria: { sql: 'cli_ocupacion_primaria', type: 'string' },
    cli_ocupacion_secundaria: { sql: 'cli_ocupacion_secundaria', type: 'string' },
    cli_lugar_nacimiento: { sql: 'cli_lugar_nacimiento', type: 'string' },
    cli_nacionalidad: { sql: 'cli_nacionalidad', type: 'number' },
    cli_otra_nacionalidad: { sql: 'cli_otra_nacionalidad', type: 'number' },
    cli_direccion: { sql: 'cli_direccion', type: 'string' },
    cli_coddep_residencia: { sql: 'cli_coddep_residencia', type: 'number' },
    cli_codmun_residencia: { sql: 'cli_codmun_residencia', type: 'number' },
    cli_ciudad: { sql: 'cli_ciudad', type: 'string' },
    cli_lab_empresa: { sql: 'cli_lab_empresa', type: 'string' },
    cli_lab_profesion: { sql: 'cli_lab_profesion', type: 'string' },
    cli_lab_cargo: { sql: 'cli_lab_cargo', type: 'string' },
    cli_lab_antiguedad: { sql: 'cli_lab_antiguedad', type: 'string' },
    cli_lab_direccion: { sql: 'cli_lab_direccion', type: 'string' },
    cli_lab_ciudad: { sql: 'cli_lab_ciudad', type: 'string' },
    cli_lab_fuente: { sql: 'cli_lab_fuente', type: 'string' },
    cli_con_nombre: { sql: 'cli_con_nombre', type: 'string' },
    cli_con_nacionalidad: { sql: 'cli_con_nacionalidad', type: 'number' },
    cli_con_codtdi: { sql: 'cli_con_codtdi', type: 'number' },
    cli_con_numero_documento: { sql: 'cli_con_numero_documento', type: 'number' },
    cli_codusr_registra: { sql: 'cli_codusr_registra', type: 'number' },
    cli_ip_registra: { sql: 'cli_ip_registra', type: 'string' },
    cli_fecha_registra: { sql: 'cli_fecha_registra', type: 'time' },
    ventana*: { sql: 'ventana*', type: 'string' },
    edad: { sql: 'edad', type: 'string' },
    tel: { sql: 'tel', type: 'string' }
  }
});
